"""Baseline: the schema `create_all` produced before Alembic.

Revision ID: 0001
Revises:
Create Date: 2026-09-30 21:38:55.846737

Autogenerated from the models, then reviewed by hand. Changes from the raw
output, each deliberate:

- The two pgvector tables use ``Vector(EMBEDDING_DIMENSIONS)`` read from
  Settings at migration time, as the models do, rather than the width of the
  machine that generated this file.
- They are created only when the ``vector`` extension can be installed. Without
  it the app runs graph-only, as it did under ``create_all``; ``db.engine.init_db``
  creates them on a later boot once the extension is available.
- Both ``index=True`` and an explicit ``Index`` exist on a few columns
  (``chunk_embeddings.project_id``/``document_id``). That duplication is what
  ``create_all`` built on every existing deployment, so the baseline keeps it;
  removing it is a separate migration.

Existing deployments (tables present, no ``alembic_version``) are not run
through this file: ``init_db`` replays the legacy bootstrap and stamps them at
this revision. See "Postgres schema migrations" in backend/CLAUDE.md.
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

from intel_platform.config import get_settings

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Width of both embedding columns, as the models read it (db/models.py).
_EMBEDDING_DIM = get_settings().embedding_dimensions

def _vector_available() -> bool:
    if context.is_offline_mode():
        # No database to ask: emit the extension and the tables, as for a
        # database that has pgvector.
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        return True
    from intel_platform.db.engine import ensure_vector_extension

    return ensure_vector_extension(op.get_bind())


def _create_vector_tables() -> None:
    op.create_table('attack_technique_embeddings',
    sa.Column('technique_id', sa.String(length=32), nullable=False, comment='Canonical ATT&CK technique id, e.g. T1566 or T1566.001'),
    sa.Column('text', sa.Text(), nullable=False, comment="Embedded text: '<name>. <description>'"),
    sa.Column('embedding', Vector(_EMBEDDING_DIM), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('technique_id')
    )
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False, comment='Neo4j Document entity ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(_EMBEDDING_DIM), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='source_url, chunk_size, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_document', 'chunk_embeddings', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_document_id'), 'chunk_embeddings', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_project_id'), 'chunk_embeddings', ['project_id'], unique=False)
    op.create_index('ix_chunk_project', 'chunk_embeddings', ['project_id'], unique=False)


def upgrade() -> None:
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='anthropic | openai | cohere | ollama'),
    sa.Column('label', sa.String(length=128), nullable=False, comment="User-friendly label, e.g. 'Personal Key', 'Team Key'"),
    sa.Column('api_key', sa.Text(), nullable=False, comment='The raw API key value'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Only one key per provider should be active at a time'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_provider'), 'api_keys', ['provider'], unique=False)
    op.create_index('ix_apikey_provider_active', 'api_keys', ['provider', 'is_active'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False, comment="Setting key, e.g. 'collection_proxy_mode'"),
    sa.Column('value', sa.Text(), nullable=False, comment='Setting value as a string'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('attack_d3fend_cache',
    sa.Column('technique_id', sa.String(length=32), nullable=False, comment='Canonical ATT&CK technique id, e.g. T1566 or T1566.001'),
    sa.Column('countermeasures', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Parsed D3FEND countermeasures: [{id, label}]'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment="When this technique's D3FEND mapping was last fetched (TTL basis)"),
    sa.PrimaryKeyConstraint('technique_id')
    )
    op.create_table('collection_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False, comment='The intelligence question or gap this collection addresses'),
    sa.Column('pir', sa.Text(), nullable=False, comment='Priority Intelligence Requirement text'),
    sa.Column('refined_pir', sa.Text(), nullable=False),
    sa.Column('pir_id', sa.UUID(), nullable=True, comment='pirs.id this plan was generated for, if any'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('routing_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="e.g. {extract_entities: true, target_project: 'xxx', store_documents: true}"),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=False),
    sa.Column('schedule_cron', sa.String(length=128), nullable=False, comment='Cron expression for recurring collection, empty for one-time'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_plans_pir_id'), 'collection_plans', ['pir_id'], unique=False)
    op.create_index(op.f('ix_collection_plans_project_id'), 'collection_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_collection_plans_status'), 'collection_plans', ['status'], unique=False)
    op.create_index('ix_plan_project_status', 'collection_plans', ['project_id', 'status'], unique=False)
    op.create_table('enrichment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False, comment="Enrichment provider name, e.g. 'rdap' | 'dns' | 'geoip'"),
    sa.Column('observable', sa.String(length=512), nullable=False, comment='Normalized (refanged) observable value that was looked up'),
    sa.Column('entity_type', sa.String(length=32), nullable=False, comment="Entity type of the observable, e.g. 'IPAddress'"),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Provider result payload — cache value + audit record'),
    sa.Column('source_url', sa.Text(), nullable=False, comment='Provider source URL, carried as relationship evidence'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Freshness horizon; NULL = never expires'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'observable', name='uq_enrichment_provider_observable')
    )
    op.create_index('ix_enrichment_provider_observable', 'enrichment_records', ['provider', 'observable'], unique=False)
    op.create_table('pir_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pir_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False, comment='Position in Pir.eeis — the element this row carries state for'),
    sa.Column('text', sa.Text(), nullable=False, comment='The EEI as written, copied from Pir.eeis so a renamed element is detectable'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending | satisfied | unmet — unmet means tried and given up on, not untried'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='Collection attempts spent. The circuit breaker: an element still unanswered after the cap is marked unmet and the run moves on.'),
    sa.Column('next_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Search queries the assessor proposed for the gap, used by the next pass'),
    sa.Column('assessment_missing', sa.Text(), nullable=False, comment='What the assessor said is still absent — the analyst-facing gap'),
    sa.Column('assessment_confidence', sa.String(length=16), nullable=False, comment='high | medium | low | unknown'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pir_requirements_pir_id'), 'pir_requirements', ['pir_id'], unique=False)
    op.create_index('ix_pir_requirements_pir_status', 'pir_requirements', ['pir_id', 'status'], unique=False)
    op.create_index(op.f('ix_pir_requirements_project_id'), 'pir_requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_pir_requirements_status'), 'pir_requirements', ['status'], unique=False)
    op.create_table('pirs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='Neo4j Project id this requirement belongs to'),
    sa.Column('title', sa.String(length=256), nullable=False, comment="Short analyst-facing label, e.g. 'PIR-1 — Actor infrastructure'"),
    sa.Column('text', sa.Text(), nullable=False, comment='The intelligence question as written by the analyst'),
    sa.Column('refined_text', sa.Text(), nullable=False, comment='LLM-refined restatement of the PIR (written back by /collection-plans/from-pir)'),
    sa.Column('eeis', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Essential Elements of Information — the sub-questions, as a list of strings'),
    sa.Column('priority', sa.String(length=16), nullable=False, comment='critical | high | medium | low — mirrors Project.priority vocabulary'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='OPEN | PARTIAL | SATISFIED | ARCHIVED'),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pir_project_status', 'pirs', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_pirs_project_id'), 'pirs', ['project_id'], unique=False)
    op.create_index(op.f('ix_pirs_status'), 'pirs', ['status'], unique=False)
    op.create_table('topic_edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False, comment='Algorithmic topic node ID (e.g. topic-0-1)'),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('edit_type', sa.String(length=20), nullable=False, comment='rename | add | delete | move'),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=False, comment='For move/add operations — target parent node ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topic_edit_node_project', 'topic_edits', ['node_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_topic_edits_node_id'), 'topic_edits', ['node_id'], unique=False)
    op.create_index(op.f('ix_topic_edits_project_id'), 'topic_edits', ['project_id'], unique=False)
    op.create_table('collection_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='file_upload | web_scrape | api_feed | database | rss_feed | watched_dir'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Type-specific params: url, selectors, query, file_format, etc.'),
    sa.Column('schedule_cron', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('collection_status', sa.String(length=20), nullable=False, comment='pending | queued | collecting | succeeded | failed | skipped | awaiting_upload'),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('total_records_acquired', sa.Integer(), nullable=False),
    sa.Column('acquisition_count', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['collection_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_plan', 'collection_sources', ['plan_id'], unique=False)
    op.create_index('ix_source_type', 'collection_sources', ['source_type'], unique=False)
    op.create_table('collection_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(length=32), nullable=False, comment='plan_started | source_queued | source_collecting | source_succeeded | source_failed | plan_completed'),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['collection_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['collection_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_created', 'collection_activity', ['created_at'], unique=False)
    op.create_index('ix_activity_plan', 'collection_activity', ['plan_id'], unique=False)
    op.create_table('data_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('file_format', sa.String(length=32), nullable=False, comment='csv, xlsx, json, jsonl, xml, parquet'),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('schema_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Column names, inferred types, sample values'),
    sa.Column('profiling', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Null rates, value distributions, date ranges, uniqueness'),
    sa.Column('preview_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='First N rows for analyst preview'),
    sa.Column('storage_path', sa.String(length=1024), nullable=False, comment='Path to stored data (local file or blob reference)'),
    sa.Column('storage_format', sa.String(length=32), nullable=False, comment='Internal storage format'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['collection_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['collection_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_plan', 'data_catalog', ['plan_id'], unique=False)
    op.create_index('ix_catalog_source', 'data_catalog', ['source_id'], unique=False)
    op.create_table('acquisition_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False, comment='SUCCESS | FAILURE | PARTIAL | SKIPPED'),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot of config at acquisition time for reproducibility'),
    sa.Column('data_catalog_id', sa.UUID(), nullable=True),
    sa.Column('entities_created', sa.Integer(), nullable=False),
    sa.Column('relationships_created', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False, comment='Neo4j Document entity ID if routed to graph'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_catalog_id'], ['data_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['collection_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['collection_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acqlog_plan', 'acquisition_log', ['plan_id'], unique=False)
    op.create_index('ix_acqlog_source', 'acquisition_log', ['source_id'], unique=False)
    op.create_index('ix_acqlog_started', 'acquisition_log', ['started_at'], unique=False)
    if _vector_available():
        _create_vector_tables()


def downgrade() -> None:
    op.drop_index('ix_acqlog_started', table_name='acquisition_log')
    op.drop_index('ix_acqlog_source', table_name='acquisition_log')
    op.drop_index('ix_acqlog_plan', table_name='acquisition_log')
    op.drop_table('acquisition_log')
    op.drop_index('ix_catalog_source', table_name='data_catalog')
    op.drop_index('ix_catalog_plan', table_name='data_catalog')
    op.drop_table('data_catalog')
    op.drop_index('ix_activity_plan', table_name='collection_activity')
    op.drop_index('ix_activity_created', table_name='collection_activity')
    op.drop_table('collection_activity')
    op.drop_index('ix_source_type', table_name='collection_sources')
    op.drop_index('ix_source_plan', table_name='collection_sources')
    op.drop_table('collection_sources')
    op.drop_index(op.f('ix_topic_edits_project_id'), table_name='topic_edits')
    op.drop_index(op.f('ix_topic_edits_node_id'), table_name='topic_edits')
    op.drop_index('ix_topic_edit_node_project', table_name='topic_edits')
    op.drop_table('topic_edits')
    op.drop_index(op.f('ix_pirs_status'), table_name='pirs')
    op.drop_index(op.f('ix_pirs_project_id'), table_name='pirs')
    op.drop_index('ix_pir_project_status', table_name='pirs')
    op.drop_table('pirs')
    op.drop_index(op.f('ix_pir_requirements_status'), table_name='pir_requirements')
    op.drop_index(op.f('ix_pir_requirements_project_id'), table_name='pir_requirements')
    op.drop_index('ix_pir_requirements_pir_status', table_name='pir_requirements')
    op.drop_index(op.f('ix_pir_requirements_pir_id'), table_name='pir_requirements')
    op.drop_table('pir_requirements')
    op.drop_index('ix_enrichment_provider_observable', table_name='enrichment_records')
    op.drop_table('enrichment_records')
    op.drop_index('ix_plan_project_status', table_name='collection_plans')
    op.drop_index(op.f('ix_collection_plans_status'), table_name='collection_plans')
    op.drop_index(op.f('ix_collection_plans_project_id'), table_name='collection_plans')
    op.drop_index(op.f('ix_collection_plans_pir_id'), table_name='collection_plans')
    op.drop_table('collection_plans')
    # Absent when the database had no pgvector; their indexes go with them.
    op.drop_table('chunk_embeddings', if_exists=True)
    op.drop_table('attack_technique_embeddings', if_exists=True)
    op.drop_table('attack_d3fend_cache')
    op.drop_table('app_settings')
    op.drop_index('ix_apikey_provider_active', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_provider'), table_name='api_keys')
    op.drop_table('api_keys')
