"""degraded events

Degraded-outcome counts flushed by each process (services/telemetry.py), so the
admin card can sum the API's and the collection worker's over the last 24 hours.
One row per (process, subsystem, reason) per flush window.

Revision ID: 1cb6b0d273f5
Revises: 99f913170802
Create Date: 2026-10-02 07:54:46.473213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb6b0d273f5'
down_revision: Union[str, Sequence[str], None] = '99f913170802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # A database whose tables came from `Base.metadata.create_all` (the test
    # suite's fixtures, a development database) may have this table already;
    # tolerate it, as 4418e903536f and 99f913170802 do. create_all builds the
    # same table.
    bind = op.get_bind()
    if sa.inspect(bind).has_table("degraded_events"):
        return
    # ### commands auto generated by Alembic, reviewed ###
    op.create_table('degraded_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process', sa.String(length=16), nullable=False, comment='api | worker'),
    sa.Column('host', sa.Text(), nullable=False, comment='Hostname of the process that counted these'),
    sa.Column('subsystem', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False, comment='When counting for this flush began (the previous flush, or process start)'),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False, comment='When this flush took the counts'),
    sa.CheckConstraint("process IN ('api', 'worker')", name='ck_degraded_events_process'),
    sa.CheckConstraint('count > 0', name='ck_degraded_events_count'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_degraded_events_window_end', 'degraded_events', ['window_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic, reviewed ###
    op.drop_index('ix_degraded_events_window_end', table_name='degraded_events')
    op.drop_table('degraded_events')
    # ### end Alembic commands ###
