"""collection jobs

Revision ID: 4418e903536f
Revises: 0001
Create Date: 2026-10-01 00:14:48.966030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4418e903536f'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False, comment='agentic | requirements (worker-run); legacy (the /collections runner)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued | running | succeeded | failed | cancelled'),
    sa.Column('worker_id', sa.String(length=128), nullable=True, comment='Process that claimed the job: worker:<host>:<pid>:<n> or api:<host>:<pid>'),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True, comment='Sanitised failure reason, safe to show an analyst; never exception text'),
    sa.Column('degraded', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Degraded outcomes during this run: {subsystem: {reason: count}}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collection_jobs_plan_created', 'collection_jobs', ['plan_id', 'created_at'], unique=False)
    op.create_index('ix_collection_jobs_status_created', 'collection_jobs', ['status', 'created_at'], unique=False)
    op.create_index('uq_collection_jobs_live_plan', 'collection_jobs', ['plan_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_collection_jobs_live_plan', table_name='collection_jobs', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_collection_jobs_status_created', table_name='collection_jobs')
    op.drop_index('ix_collection_jobs_plan_created', table_name='collection_jobs')
    op.drop_table('collection_jobs')
    # ### end Alembic commands ###
