"""project members

Who may read, write and manage each project (api/access.py). A project with no
rows is open to every authenticated user, so existing projects behave as before.

Revision ID: 99f913170802
Revises: 4418e903536f
Create Date: 2026-10-01 23:12:38.907436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f913170802'
down_revision: Union[str, Sequence[str], None] = '4418e903536f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # A database whose tables came from `Base.metadata.create_all` (the test
    # suite's fixtures, a development database) may have this table already;
    # adoption stamps such a database at the baseline, so tolerate it, as
    # 4418e903536f does for collection_jobs. create_all builds the same table.
    bind = op.get_bind()
    if sa.inspect(bind).has_table("project_members"):
        return
    # ### commands auto generated by Alembic, reviewed ###
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='Neo4j Project id'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='Neo4j User username'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='owner | editor | viewer'),
    sa.Column('added_by', sa.String(length=128), nullable=False, comment='Username that added this member'),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='ck_project_members_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'username', name='uq_project_members_project_username')
    )
    op.create_index(op.f('ix_project_members_username'), 'project_members', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic, reviewed ###
    op.drop_index(op.f('ix_project_members_username'), table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
